BLUE = (0, 0, 255)
BLACK = (0, 0, 0)
RED = (255, 0, 0)
YELLOW = (255, 255, 0)

ROW_COUNT = 6
COLUMN_COUNT = 7
SQUARE_SIZE = 100
RADIUS = int(SQUARE_SIZE/2 - 5)

WIDTH = COLUMN_COUNT * SQUARE_SIZE
HEIGHT = (ROW_COUNT+1) * SQUARE_SIZE
SIZE = (WIDTH, HEIGHT)

PLAYER1_COLOR = RED
PLAYER2_COLOR = YELLOW
PLAYER1_NAME = 'Player 1'
PLAYER2_NAME = 'Player 2'

PLAY_WITH_AI = True
AI_NAME = 'AI'
AI_LEVEL = 3
